// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	auth "github.com/vliubezny/gnotify/internal/auth"
	reflect "reflect"
)

// MockAuthenticator is a mock of Authenticator interface
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenthicate mocks base method
func (m *MockAuthenticator) Authenthicate(token string) (auth.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenthicate", token)
	ret0, _ := ret[0].(auth.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenthicate indicates an expected call of Authenthicate
func (mr *MockAuthenticatorMockRecorder) Authenthicate(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenthicate", reflect.TypeOf((*MockAuthenticator)(nil).Authenthicate), token)
}
